### ISSUE TITLE
where is _roi_align?

### ISSUE THREAD

**Issue by townim-faisal** [luulinh90s/Neural-Baby-Talk-python3#11]
I do not found _roi_align? Here is the error
`Traceback (most recent call last):                                                                                        File "main.py", line 18, in <module>                                                                                      from misc import utils, eval_utils, AttModel                                                                          File "C:\Users\BS197\Downloads\New folder\Neural-Baby-Talk-python3-master\misc\AttModel.py", line 10, in <module>         from misc.model import AttModel                                                                                       File "C:\Users\BS197\Downloads\New folder\Neural-Baby-Talk-python3-master\misc\model.py", line 14, in <module>            from pooling.roi_align.modules.roi_align import RoIAlignAvg                                                           File "C:\Users\BS197\Downloads\New folder\Neural-Baby-Talk-python3-master\pooling\roi_align\modules\roi_align.py", line 3, in <module>                                                                                                            from ..functions.roi_align import RoIAlignFunction                                                                    File "C:\Users\BS197\Downloads\New folder\Neural-Baby-Talk-python3-master\pooling\roi_align\functions\roi_align.py", line 3, in <module>                                                                                                          from .._ext import roi_align                                                                                          File "C:\Users\BS197\Downloads\New folder\Neural-Baby-Talk-python3-master\pooling\roi_align\_ext\roi_align\__init__.py", line 3, in <module>                                                                                                      from ._roi_align import lib as _lib, ffi as _ffi                                                                    ModuleNotFoundError: No module named 'pooling.roi_align._ext.roi_align._roi_align' `

**Comment by giangnguyen2412** [comment]
try here: https://github.com/deneb2016/WSDDN.pytorch/issues/1

**Comment by townim-faisal** [comment]
After running make.sh, I have found following errors, though I have installed gcc:
```
/home/nsu/Downloads/Neural-Baby-Talk-python3-master/pooling/roi_align
generating /tmp/tmpy2nkwe_2/_roi_align.c
setting the current directory to '/tmp/tmpy2nkwe_2'
running build_ext
building '_roi_align' extension
gcc -pthread -B /home/nsu/anaconda3/envs/neuralbabytalk/compiler_compat -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -I/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include -I/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/torch/utils/ffi/../../lib/include/TH -I/home/nsu/anaconda3/envs/neuralbabytalk/include/python3.5m -c _roi_align.c -o ./_roi_align.o -std=c99
gcc -pthread -shared -L/home/nsu/anaconda3/envs/neuralbabytalk/lib -B /home/nsu/anaconda3/envs/neuralbabytalk/compiler_compat -Wl,-rpath=/home/nsu/anaconda3/envs/neuralbabytalk/lib,--no-as-needed -std=c99 ./_roi_align.o /home/nsu/Downloads/Neural-Baby-Talk-python3-master/pooling/roi_align/src/roi_align_kernel.cu.o -o ./_roi_align.so
gcc: error: /home/nsu/Downloads/Neural-Baby-Talk-python3-master/pooling/roi_align/src/roi_align_kernel.cu.o: No such file or directory
Traceback (most recent call last):
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/distutils/unixccompiler.py", line 197, in link
    self.spawn(linker + ld_args)
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/cffi/ffiplatform.py", line 51, in _build
    dist.run_command('build_ext')
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/distutils/unixccompiler.py", line 199, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "build.py", line 36, in <module>
    ffi.build()
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/torch/utils/ffi/__init__.py", line 189, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/torch/utils/ffi/__init__.py", line 111, in _build_extension
    outfile = ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/cffi/api.py", line 697, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/cffi/recompiler.py", line 1520, in recompile
    compiler_verbose, debug)
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/home/nsu/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.error.VerificationError: LinkError: command 'gcc' failed with exit status 1
```

**Comment by townim-faisal** [comment]
I have solved it by trying this: https://github.com/jwyang/faster-rcnn.pytorch/issues/112
