### ISSUE TITLE
noc_test_freq.p file is missing in coco-caption tool

### ISSUE THREAD

**Issue by townim-faisal** [luulinh90s/Neural-Baby-Talk-python3#15]
I have used your coco-caption [tool](https://github.com/luulinh90s/coco-caption) but got this following error:
```
Traceback (most recent call last):
  File "main.py", line 358, in <module>
    lang_stats = eval(opt)
  File "main.py", line 170, in eval
    lang_stats = utils.noc_eval(predictions, str(1), opt.val_split, opt)
  File "/home/ara2/Downloads/Neural-Baby-Talk-python3-master/misc/utils.py", line 316, in noc_eval
    out = score_dcc(gt_template_novel, gt_template_train, pred, noc_object, split, cache_path)
  File "tools/sentence_gen_tools/coco_eval.py", line 123, in score_dcc
    score_dict = dcc_evaluator.get_dcc_scores()
  File "tools/sentence_gen_tools/coco_eval.py", line 58, in get_dcc_scores
    score, scores = scorer.compute_score(gts, res)
  File "tools/coco-caption/pycocoevalcap/cider/cider.py", line 45, in compute_score
    (score, scores) = cider_scorer.compute_score(self._dfMode)
  File "tools/coco-caption/pycocoevalcap/cider/cider_scorer.py", line 206, in compute_score
    df_mode + '.p'), 'r'))
FileNotFoundError: [Errno 2] No such file or directory: 'tools/coco-caption/data/noc_test_freq.p'
```

**Comment by jrryzh** [comment]
Did you solve this? I ran into the same problem.
