### ISSUE TITLE
KeyError: 'type'

### ISSUE THREAD

**Issue by ghost** [luulinh90s/Neural-Baby-Talk-python3#4]
I try your training code. But  return the "KeyError: 'type'"
Traceback (most recent call last):
  File "/home/gyq/workspace/nbt3/main.py", line 215, in <module>
    dataset = DataLoader(opt, split='train')
  File "/home/gyq/workspace/nbt3/misc/dataloader_coco.py", line 118, in __init__
    self.coco_train = COCO(det_train_path)
  File "tools/coco-caption/pycocotools/coco.py", line 79, in __init__
    self.createIndex()
  File "tools/coco-caption/pycocotools/coco.py", line 96, in createIndex
    if self.dataset['type'] == 'instances':
KeyError: 'type'
How can I Slove this problem?
It seems the "instance2014.json "  don't have the key "type".

**Comment by giangnguyen2412** [comment]
I have a repo of modified coco-caption/ for python 3. Did you try it, clone
it to replace your current coco-caption/ dir. Here:
https://github.com/luulinh90s/coco-caption

Vào 21:54, T.4, 22 Th5, 2019 yizhiyua <notifications@github.com> đã viết:

**Comment by ghost** [comment]
Thank you for your patient reply. I have a question. When we build the enviroment , we run "pip install pycocotools" comment to install pycocotools package in our python site package.  which one is used in this code? pycocotools2.0 in python site package or pycocotools 1.0 in coco-caption folder?

**Comment by giangnguyen2412** [comment]
No

Use my modified pycocotools will work smoothly on python3


Vào 19:33, T.5, 23 Th5, 2019 yizhiyua <notifications@github.com> đã viết:

**Comment by giangnguyen2412** [comment]
Use the one in coco caption folder

Vào 20:56, T.5, 23 Th5, 2019 Giang Nguyễn <nguyengiangbkhn@gmail.com> đã
viết:

**Comment by ghost** [comment]
Thank You. I've tried your version of coco-caption and slove the problem above. But it seems there are some problems with Dataloader. Have you ever met this problem?
Traceback (most recent call last):
  File "main.py", line 355, in <module>
    train(epoch, opt)
  File "main.py", line 51, in train
    data = data_iter.next()
  File "/home/gyq/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 336, in __next__
    return self._process_next_batch(batch)
  File "/home/gyq/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
KeyError: 'Traceback (most recent call last):\n  File "/home/gyq/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/gyq/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 106, in <listcomp>\n    samples = collate_fn([dataset[i] for i in batch_indices])\n  File "/home/gyq/workspace/Neural-Baby-Talk-python3/misc/dataloader_coco.py", line 272, in __getitem__\n    cap_seq[i,k,0] = self.wtoi[caption[j]]\nKeyError: \'a\'\n'

**Comment by giangnguyen2412** [comment]
Key error? I think the problem is from data, not dataloader

Vào 23:59, T.5, 23 Th5, 2019 yizhiyua <notifications@github.com> đã viết:

**Comment by giangnguyen2412** [comment]
Anyway,

Someone has the same problem but in the repo of the paper author Jiasen Lu.
Could you pls take a look at his repo 's issues?

Vào 23:59, T.5, 23 Th5, 2019 yizhiyua <notifications@github.com> đã viết:

**Comment by giangnguyen2412** [comment]
Refer here: https://github.com/jiasenlu/NeuralBabyTalk/issues/33

**Comment by ghost** [comment]
Thank you for your reply. I've solved the keyerror 'type' with the new version of pycocotools in cocoapi, not using the one in coco-caption folder. I don't know if it's right, but it can work.
And the second problem is caused by the dic_coco.json file. I changed the file by mistake.
Thank you for your patient reply. Very appreciate.
If I have other questions, hoping to get your instruction later.

**Comment by giangnguyen2412** [comment]
Warmly welcome :) we are all studying

Vào 13:01, T.6, 24 Th5, 2019 yizhiyua <notifications@github.com> đã viết:

**Comment by ghost** [comment]
Hi, sry to bother you again. It seems there is some problem with the evaluation. Have you ever met this probelm? Traceback (most recent call last):
  File "/home/qyg/workspace/nbt3/main.py", line 358, in <module>
    lang_stats = eval(opt)
  File "/home/qyg/workspace/nbt3/main.py", line 170, in eval
    lang_stats = utils.noc_eval(predictions, str(1), opt.val_split, opt)
  File "/home/qyg/workspace/nbt3/misc/utils.py", line 316, in noc_eval
    out = score_dcc(gt_template_novel, gt_template_train, pred, noc_object, split, cache_path)
  File "tools/sentence_gen_tools/coco_eval.py", line 123, in score_dcc
    score_dict = dcc_evaluator.get_dcc_scores()
  File "tools/sentence_gen_tools/coco_eval.py", line 58, in get_dcc_scores
    score, scores = scorer.compute_score(gts, res)
  File "tools/coco-caption/pycocoevalcap/bleu/bleu.py", line 23, in compute_score
    assert(gts.keys() == res.keys())
AssertionError
The key in gts and res doesn't match

**Comment by giangnguyen2412** [comment]
Sorry I am busy these days. Solve it yourself and if not, reply here and I
will go back soon
Giang. Nguyen

**Comment by jhhuang96** [comment]
> 
> 
> Thank You. I've tried your version of coco-caption and slove the problem above. But it seems there are some problems with Dataloader. Have you ever met this problem?
> Traceback (most recent call last):
> File "main.py", line 355, in
> train(epoch, opt)
> File "main.py", line 51, in train
> data = data_iter.next()
> File "/home/gyq/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 336, in **next**
> return self._process_next_batch(batch)
> File "/home/gyq/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 357, in _process_next_batch
> raise batch.exc_type(batch.exc_msg)
> KeyError: 'Traceback (most recent call last):\n File "/home/gyq/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 106, in _worker_loop\n samples = collate_fn([dataset[i] for i in batch_indices])\n File "/home/gyq/anaconda3/envs/neuralbabytalk/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 106, in \n samples = collate_fn([dataset[i] for i in batch_indices])\n File "/home/gyq/workspace/Neural-Baby-Talk-python3/misc/dataloader_coco.py", line 272, in **getitem**\n cap_seq[i,k,0] = self.wtoi[caption[j]]\nKeyError: 'a'\n'

Hello, I encountered this same error and how did you solve this error?

**Comment by giangnguyen2412** [comment]
Hi @yizhiyua , here, in BLEU, we are computing the overlapping between label caption and predicted captions, but the keys are not match, then I think your data has a problem. Did you solve it? sorry I just came back from my final exams.

**Comment by PRYUS** [comment]
hi, @yizhiyua did you solve that assertion error. I have got the same problem with BLEU evaluation.

**Comment by Longcuirong** [comment]
when I 

> coco-caption/ dir. Here: https://github.com/luulinh90s/coco-caption
when I use your coco-caption dir ,there still exsists type error???
![image](https://user-images.githubusercontent.com/18166739/72130839-9af3fd80-33b5-11ea-820d-736cc061e91b.png)
